### ISSUE TITLE
KoKo容器突然exit

### ISSUE THREAD

**Issue by abuxliu** [jumpserver/koko#9]
1. 版本
jumpserver/jms_koko@sha256:6249ef49eac1965563d68b8b5d8a7fab18a7b517c2ba9b214eff70bef01eabfe

2. 现象
容器退出

3. 日志
abuxliu@koko:~$ sudo docker logs -t --since="2019-06-23T00:00:00" 51477d23898e
2019-06-23T12:18:07.408220738Z 2019-06-23 20:18:07
2019-06-23T12:18:07.408271538Z Coco version 1.5.0, more see https://www.jumpserver.org
2019-06-23T12:18:07.408278938Z Quit the server with CONTROL-C.
2019-06-23T14:23:37.409407756Z 2019-06-23 22:23:37 [ERRO] Post http://172.16.0.211:8080/api/terminal/v1/terminal/status/: EOF
2019-06-23T14:44:05.677972838Z 2019-06-23 22:44:05 [ERRO] Read from user err: EOF
2019-06-24T00:54:55.237482754Z 2019-06-24 08:54:55 [ERRO] Read from user err: EOF
2019-06-24T01:00:22.651592489Z 2019-06-24 09:00:22 [ERRO] Read from user err: EOF
2019-06-24T01:09:26.779541426Z panic: runtime error: slice bounds out of range
2019-06-24T01:09:26.779570126Z 
2019-06-24T01:09:26.779574026Z goroutine 34172 [running]:
2019-06-24T01:09:26.779576926Z github.com/jumpserver/koko/pkg/proxy.(*SwitchSession).generateCommandResult(0xc000226210, 0xc00031e600, 0xfd, 0xc000494100, 0x33, 0xc00100aa80)
2019-06-24T01:09:26.779580426Z 	/go/src/github.com/jumpserver/koko/pkg/proxy/switch.go:92 +0x3f3
2019-06-24T01:09:26.779583826Z github.com/jumpserver/koko/pkg/proxy.(*SwitchSession).recordCommand(0xc000226210)
2019-06-24T01:09:26.779587026Z 	/go/src/github.com/jumpserver/koko/pkg/proxy/switch.go:72 +0xc4
2019-06-24T01:09:26.779590026Z created by github.com/jumpserver/koko/pkg/proxy.(*SwitchSession).Bridge
2019-06-24T01:09:26.779593826Z 	/go/src/github.com/jumpserver/koko/pkg/proxy/switch.go:138 +0x21c

**Comment by LeeEirc** [comment]
使用了什么命令之后，容器退出？ @abuxliu

**Comment by abuxliu** [comment]
1. 容器启动后未对容器操作命令

2. 客户端操作exit命令后容器退出，如下
```
页码: 2, 数量: 3, 总页数: 2, 总数量: 26
Opt> exit
```

**Comment by abuxliu** [comment]
> 使用了什么命令之后，容器退出？ @abuxliu

容器启动后未对容器操作命令

客户端操作exit命令后容器退出，如下

```
页码: 2, 数量: 3, 总页数: 2, 总数量: 26
Opt> exit
```

**Comment by LeeEirc** [comment]
> > 使用了什么命令之后，容器退出？ @abuxliu
> 
> 容器启动后未对容器操作命令
> 
> 客户端操作exit命令后容器退出，如下
> 
> ```
> 页码: 2, 数量: 3, 总页数: 2, 总数量: 26
> Opt> exit
> ```

已经修复。

**Comment by abuxliu** [comment]
谢谢～
